"""
Phase 5 — Report generation.
Takes fully-enriched pipeline items and produces a markdown table report
for Product Owners.

Input items must have (set by earlier pipeline stages):
    extracted_issue  (str)  — clean English sentence
    domain           (str)  — Payment / QR Code / Account / App Performance / Merchant / Other
    segment          (str)  — sub-category
    mentions         (int)  — how many posts were merged (default 1)
    sources          (str)  — comma-separated source names
    ids              (list) — original item IDs

This module also calls KB search internally to add "suggested_approach"
before rendering, so callers don't need to.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from knowledge_base.search import get_suggested_approach
from llm_client import llm

_SUMMARY_SYSTEM = (
    "You are a Product Owner report writer for Zalopay. "
    "Write a 2–3 sentence executive summary of the complaint trends shown. "
    "Be factual, concise, and actionable. Plain text only — no markdown."
)

OUTPUT_DIR = Path(__file__).parent.parent / "output"


def generate_report(items: list[dict], job_name: str = "Social Media") -> str:
    """
    Build a markdown complaint report from enriched pipeline items.

    Returns:
        Multi-line markdown string with header, executive summary, and issue table.
    """
    if not items:
        return _empty_report(job_name)

    rows = _build_rows(items)
    today = date.today().isoformat()
    total_mentions = sum(r["mentions"] for r in rows)

    summary = _executive_summary(rows, today, job_name)

    lines = [
        f"# Zalopay Complaint Report — {job_name}",
        f"**Date**: {today} | **Total Issues**: {len(rows)} | **Total Mentions**: {total_mentions}",
        "",
        "## Executive Summary",
        summary,
        "",
        "## Issue Table",
        "",
        "| Domain | Segment | Issue | Mentions | Sources | Suggested Approach |",
        "|--------|---------|-------|----------|---------|-------------------|",
    ]

    for r in rows:
        approach = r["suggested_approach"].replace("\n", " ").replace("|", "/")
        if len(approach) > 120:
            approach = approach[:117] + "..."
        lines.append(
            f"| {r['domain']} | {r['segment']} | {r['issue']} "
            f"| {r['mentions']} | {r['sources']} | {approach} |"
        )

    lines += ["", "---", "*Generated by Zalopay Analytics Agent*"]
    return "\n".join(lines)


def save_report(report: str, job_name: str) -> Path:
    """Write report to output/<timestamp>_<job>.md and return the path."""
    from datetime import datetime

    OUTPUT_DIR.mkdir(exist_ok=True)
    slug = job_name.lower().replace(" ", "_")
    filename = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{slug}.md"
    path = OUTPUT_DIR / filename
    path.write_text(report, encoding="utf-8")
    return path


# ── Internal helpers ───────────────────────────────────────────────────────


def _build_rows(items: list[dict]) -> list[dict]:
    rows = []
    for item in items:
        approach = get_suggested_approach(item["extracted_issue"])
        rows.append({
            "domain":             item.get("domain", "Other"),
            "segment":            item.get("segment", "General"),
            "issue":              item["extracted_issue"],
            "mentions":           item.get("mentions", 1),
            "sources":            item.get("sources", item.get("source", "unknown")),
            "suggested_approach": approach,
        })
    rows.sort(key=lambda r: r["mentions"], reverse=True)
    return rows


def _executive_summary(rows: list[dict], today: str, job_name: str) -> str:
    top = rows[:10]
    issue_list = "\n".join(
        f"- {r['domain']}/{r['segment']}: {r['issue']} ({r['mentions']} mention(s))"
        for r in top
    )
    return llm.chat(
        system=_SUMMARY_SYSTEM,
        user=f"Report: {job_name}, {today}\n\n{issue_list}",
        max_tokens=150,
        fast=False,
    )


def _empty_report(job_name: str) -> str:
    today = date.today().isoformat()
    return (
        f"# Zalopay Complaint Report — {job_name}\n"
        f"**Date**: {today} | **Total Issues**: 0 | **Total Mentions**: 0\n\n"
        "No issues found for this reporting period.\n"
        "\n---\n*Generated by Zalopay Analytics Agent*"
    )
