"""
Phase 5 — Report generation.
Takes fully-enriched pipeline items and produces a markdown table report
for Product Owners.

Input items must have (set by earlier pipeline stages):
    extracted_issue  (str)  — clean English sentence
    domain           (str)  — Payment / QR Code / Account / App Performance / Merchant / Other
    segment          (str)  — sub-category
    mentions         (int)  — how many posts were merged (default 1)
    sources          (str)  — comma-separated source names
    ids              (list) — original item IDs

This module also calls KB search internally to add "suggested_approach"
before rendering, so callers don't need to.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from knowledge_base.search import get_suggested_approach
from llm_client import llm

_BRAND_RE = re.compile(r"\bzalo\s*pay\b", re.IGNORECASE)


def _fix_brand(text: str) -> str:
    """Normalize all casing variants of the app name to the official 'Zalopay'."""
    return _BRAND_RE.sub("Zalopay", text)

OUTPUT_DIR = Path(__file__).parent.parent / "output"

_SUMMARY_SYSTEM = (
    "You are a Product Owner report writer for Zalopay. "
    "Write a 2–3 sentence executive summary of the complaint trends shown. "
    "Be factual, concise, and actionable. Plain text only — no markdown. "
    "Always refer to the app as 'Zalopay' (capital Z only)."
)

_BRAND_NORMALIZE_SYSTEM = (
    "You are a text editor. Replace every informal or misspelled reference to the "
    "Zalopay payment app — such as 'ví zalo', 'ví điện tử zalo', 'app zalo', "
    "'zalopay', 'ZaloPay', 'ZALOPAY', 'zalo pay', or any other variant — with the "
    "official name 'Zalopay'. Return only the corrected text, word for word. "
    "Do not change anything else."
)


def generate_report(items: list[dict], job_name: str = "Social Media") -> str:
    """
    Build a markdown complaint report from enriched pipeline items.

    Returns:
        Multi-line markdown string with header, executive summary, and issue table.
    """
    if not items:
        return _empty_report(job_name)

    rows = _build_rows(items)
    today = date.today().isoformat()
    total_mentions = sum(r["mentions"] for r in rows)

    summary = _executive_summary(rows, today, job_name)

    lines = [
        f"# Zalopay Complaint Report — {job_name}",
        f"**Date**: {today} | **Total Issues**: {len(rows)} | **Total Mentions**: {total_mentions}",
        "",
        "## Executive Summary",
        summary,
        "",
        "## Issue Table",
        "",
        "| Domain | Segment | Issue | Mentions | Sources | Reference Links | Screenshots | Suggested Approach |",
        "|--------|---------|-------|----------|---------|-----------------|-------------|-------------------|",
    ]

    for r in rows:
        approach = r["suggested_approach"].replace("\n", " ").replace("|", "/")
        if len(approach) > 120:
            approach = approach[:117] + "..."
            
        # Format Links
        urls = r.get("post_urls", [])
        ids = r.get("ids", [])
        links_parts = []
        if urls:
            for idx, url in enumerate(urls):
                links_parts.append(f"[Link {idx+1}]({url})")
            links_str = "<br>".join(links_parts)
        elif ids:
            import config
            for item_id in ids:
                if r["sources"].lower() == "jira" and config.JIRA_URL:
                    jira_base = config.JIRA_URL.rstrip('/')
                    links_parts.append(f"[{item_id}]({jira_base}/browse/{item_id})")
                else:
                    links_parts.append(item_id)
            links_str = "<br>".join(links_parts)
        else:
            links_str = "—"
            
        # Format Screenshots — onclick opens full-size in new tab via window.open()
        # (<a href="data:..."> is blocked by Chrome; window.open from onclick is not)
        _onclick = "(function(s){var w=window.open('','_blank');w.document.write('<img src='+JSON.stringify(s)+' style=max-width:100%>');w.document.close()})(this.src)"
        images = r.get("images") or []
        img_parts = []
        for img_data in images:
            if not img_data:
                continue
            src = img_data if img_data.startswith("data:") else f"data:image/png;base64,{img_data}"
            img_parts.append(
                f'<img src="{src}" width="80" onclick="{_onclick}" '
                f'style="cursor:zoom-in;border-radius:4px;border:1px solid #334155;display:inline-block;margin:2px;" />'
            )
        screenshots_str = " ".join(img_parts) if img_parts else "—"

        lines.append(
            f"| {r['domain']} | {r['segment']} | {r['issue']} "
            f"| {r['mentions']} | {r['sources']} | {links_str} | {screenshots_str} | {approach} |"
        )

    lines += ["", "---", "*Generated by Zalopay Analytics Agent*"]
    return _fix_brand("\n".join(lines))


def save_report(report: str, job_name: str) -> Path:
    """Write report to output/<timestamp>_<job>.md and return the path."""
    from datetime import datetime

    OUTPUT_DIR.mkdir(exist_ok=True)
    slug = job_name.lower().replace(" ", "_")
    filename = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{slug}.md"
    path = OUTPUT_DIR / filename
    path.write_text(report, encoding="utf-8")
    return path


# ── Internal helpers ───────────────────────────────────────────────────────


def _build_rows(items: list[dict]) -> list[dict]:
    rows = []
    for item in items:
        approach = get_suggested_approach(item["extracted_issue"])
        
        post_urls = item.get("post_urls", [])
        if not post_urls and item.get("post_url"):
            post_urls = [item["post_url"]]
            
        images = item.get("all_images", [])
        if not images and item.get("images"):
            images = item["images"]
        if isinstance(images, str):
            images = [images]
            
        rows.append({
            "domain":             item.get("domain", "Other"),
            "segment":            item.get("segment", "General"),
            "issue":              item["extracted_issue"],
            "mentions":           item.get("mentions", 1),
            "sources":            item.get("sources", item.get("source", "unknown")),
            "suggested_approach": approach,
            "post_urls":          post_urls,
            "images":             images,
            "ids":                item.get("ids", [item.get("id")])
        })
    rows.sort(key=lambda r: r["mentions"], reverse=True)
    return rows


def _executive_summary(rows: list[dict], today: str, job_name: str) -> str:
    top = rows[:10]
    issue_list = "\n".join(
        f"- {r['domain']}/{r['segment']}: {r['issue']} ({r['mentions']} mention(s))"
        for r in top
    )
    summary = llm.chat(
        system=_SUMMARY_SYSTEM,
        user=f"Report: {job_name}, {today}\n\n{issue_list}",
        max_tokens=150,
        fast=False,
    )
    return llm.chat(
        system=_BRAND_NORMALIZE_SYSTEM,
        user=summary,
        max_tokens=200,
        fast=True,
    )


def _empty_report(job_name: str) -> str:
    today = date.today().isoformat()
    return _fix_brand(
        f"# Zalopay Complaint Report — {job_name}\n"
        f"**Date**: {today} | **Total Issues**: 0 | **Total Mentions**: 0\n\n"
        "No issues found for this reporting period.\n"
        "\n---\n*Generated by Zalopay Analytics Agent*"
    )
