"""
Phase 5 tests — Report Generator & Guardrails

Usage:
    .venv/bin/python test_phase5.py

Notes:
  - Guardrails tests: no API key needed
  - Generator tests: LLM call for executive summary — skipped if quota exhausted
"""

import os
import sys
sys.path.insert(0, ".")


# ── Guardrails ─────────────────────────────────────────────────────────────

def test_guardrails_valid_report():
    print("=" * 50)
    print("TEST: guardrails — accepts a well-formed report")
    print("=" * 50)
    from report.guardrails import check_report

    report = (
        "# Zalopay Complaint Report — Social Media\n"
        "**Date**: 2026-06-10 | **Total Issues**: 2 | **Total Mentions**: 5\n\n"
        "## Executive Summary\n"
        "Two issue types detected.\n\n"
        "## Issue Table\n\n"
        "| Domain | Segment | Issue | Mentions | Sources | Suggested Approach |\n"
        "|--------|---------|-------|----------|---------|-------------------|\n"
        "| Payment | Top-up | Visa card top-up failing with error E5001 | 3 | facebook | 1. Check card. |\n"
        "| QR Code | Payment | QR code scan failing at merchant terminal | 2 | threads | 1. Restart. |\n"
        "\n---\n*Generated by Zalopay Analytics Agent*"
    )
    items = [
        {"domain": "Payment", "segment": "Top-up", "extracted_issue": "Visa card top-up failing with error E5001"},
        {"domain": "QR Code", "segment": "Payment", "extracted_issue": "QR code scan failing at merchant terminal"},
    ]
    result = check_report(report, items)
    print(f"  ok     : {result['ok']}")
    print(f"  issues : {result['issues']}")
    assert result["ok"], f"Expected ok=True, got issues: {result['issues']}"
    print("  ✅ pass\n")


def test_guardrails_catches_missing_table():
    print("=" * 50)
    print("TEST: guardrails — catches missing table")
    print("=" * 50)
    from report.guardrails import check_report

    report = (
        "# Zalopay Complaint Report — Social Media\n"
        "**Date**: 2026-06-10\n\n"
        "## Executive Summary\nSome issues.\n"
    )
    items = [{"domain": "Payment", "extracted_issue": "Top-up failed"}]
    result = check_report(report, items)
    print(f"  ok     : {result['ok']}")
    print(f"  issues : {result['issues']}")
    assert not result["ok"]
    assert any("table" in p.lower() for p in result["issues"])
    print("  ✅ pass (correctly caught missing table)\n")


def test_guardrails_catches_missing_domain():
    print("=" * 50)
    print("TEST: guardrails — catches missing domain in report")
    print("=" * 50)
    from report.guardrails import check_report

    report = (
        "# Zalopay Complaint Report — Social Media\n"
        "**Date**: 2026-06-10\n\n"
        "## Executive Summary\nPayment issues detected.\n\n"
        "## Issue Table\n\n"
        "| Domain | Segment | Issue | Mentions | Sources | Suggested Approach |\n"
        "|--------|---------|-------|----------|---------|-------------------|\n"
        "| Payment | Top-up | Visa failing | 3 | facebook | 1. Check. |\n"
        "\n---\n*Generated by Zalopay Analytics Agent*"
    )
    items = [
        {"domain": "Payment", "extracted_issue": "Visa failing"},
        {"domain": "Account", "extracted_issue": "OTP not received"},  # Account missing from report
    ]
    result = check_report(report, items)
    print(f"  ok     : {result['ok']}")
    print(f"  issues : {result['issues']}")
    assert not result["ok"]
    assert any("Account" in p for p in result["issues"])
    print("  ✅ pass (correctly caught missing domain)\n")


def test_guardrails_empty_items():
    print("=" * 50)
    print("TEST: guardrails — empty items list")
    print("=" * 50)
    from report.guardrails import check_report

    report = (
        "# Zalopay Complaint Report — Social Media\n"
        "**Date**: 2026-06-10 | **Total Issues**: 0 | **Total Mentions**: 0\n\n"
        "No issues found for this reporting period.\n"
        "\n---\n*Generated by Zalopay Analytics Agent*"
    )
    result = check_report(report, [])
    print(f"  ok     : {result['ok']}")
    print(f"  issues : {result['issues']}")
    assert result["ok"], f"Empty-items report should pass guardrails: {result['issues']}"
    print("  ✅ pass\n")


# ── Generator ──────────────────────────────────────────────────────────────

def test_generator_empty_input():
    print("=" * 50)
    print("TEST: generator — empty items returns empty report")
    print("=" * 50)
    from report.generator import generate_report

    report = generate_report([], job_name="Jira")
    print(f"  Report preview: {report[:80]!r}")
    assert "Total Issues**: 0" in report
    assert "No issues found" in report
    print("  ✅ pass\n")


def test_generator_live():
    """Live test — uses KB search (embeddings, no API) + LLM for exec summary."""
    print("=" * 50)
    print("TEST: generator — live report with KB search + LLM exec summary")
    print("=" * 50)

    import config
    if not config.LLM_API_KEY:
        print("  ⏭  Skipped — LLM_API_KEY not set\n")
        return

    from report.generator import generate_report
    from report.guardrails import check_report

    items = [
        {
            "id": "FB-001", "source": "facebook",
            "extracted_issue": "Visa card top-up failing with error E5001",
            "domain": "Payment", "segment": "Top-up",
            "mentions": 3, "sources": "facebook, threads",
            "ids": ["FB-001", "TH-002", "FB-003"],
        },
        {
            "id": "FB-004", "source": "facebook",
            "extracted_issue": "QR code scan failing at merchant terminal",
            "domain": "QR Code", "segment": "Payment",
            "mentions": 2, "sources": "facebook",
            "ids": ["FB-004", "TH-005"],
        },
        {
            "id": "JR-001", "source": "jira",
            "extracted_issue": "OTP SMS not delivered to user mobile",
            "domain": "Account", "segment": "OTP",
            "mentions": 1, "sources": "jira",
            "ids": ["JR-001"],
        },
    ]

    try:
        report = generate_report(items, job_name="Social Media")
    except Exception as e:
        err = str(e)
        if any(k in err for k in ("RESOURCE_EXHAUSTED", "quota", "ConnectTimeout", "timeout")):
            print(f"  ⏭  Skipped — API error: {type(e).__name__}\n")
            return
        raise

    print(report)
    print()

    result = check_report(report, items)
    print(f"  Guardrails ok  : {result['ok']}")
    if result["issues"]:
        print(f"  Guardrails warn: {result['issues']}")

    assert result["ok"], f"Report failed guardrails: {result['issues']}"
    assert "Payment" in report
    assert "QR Code" in report
    assert "Account" in report
    print("  ✅ pass\n")


if __name__ == "__main__":
    # Guardrails — no API key needed
    test_guardrails_valid_report()
    test_guardrails_catches_missing_table()
    test_guardrails_catches_missing_domain()
    test_guardrails_empty_items()

    # Generator
    test_generator_empty_input()
    test_generator_live()

    print("=" * 50)
    print("All Phase 5 tests complete ✅")
